export const GET_CARTITEMS_NUMBER = "APP/GET_CART_ITEMS/GET_CARTITEMS_NUMBER";
export const GET_CARTITEMS_NUMBER_SUCCESS = "APP/GET_CART_ITEMS/GET_CARTITEMS_NUMBER_SUCCESS";
export const GET_CARTITEMS_NUMBER_FAILURE = "APP/GET_CART_ITEMS/GET_CARTITEMS_NUMBER_FAILURE";

